<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ajado_random_backgrounds"
 *
 * Auto generated by Extension Builder 2014-08-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ajado Random Backgrounds',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Elvis Tavasja',
	'author_email' => 'elvis@ajado.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);